name: Tests

on: 
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      '*'

jobs:
    Tests:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
      
          - name: Run Tests
            run: |
              docker run --rm -v $PWD:/app composer sh -c \
              "composer install --profile --ignore-platform-reqs && composer test"